DROP TABLE IF EXISTS 'student';
CREATE TABLE 'student' (
	'STUDENT_ID' INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	'STUDENT_NAME' VARCHAR(30) NOT NULL,
	'STUDENT_AGE' SMALLINT NOT NULL,
	PRIMARY KEY ('STUDENT_ID') USING BTREE,
	UNIQUE KEY 'UNI_STUDENT_NAME' ('STUDENT_NAME')
) ENGINE=InnoDB DEFAULT CHARSET=utf8;